flags = -Wall -Wno-unknown-pragmas
libs = ../lib/token.c ../lib/symbol.c ../lib/lexical_analyzer.c ../lib/domain_analyzer.c ../lib/value.c ../lib/virtual_machine.c ../lib/instruction.c

prog:
	gcc $(flags) -o main.exe main.c $(libs)
