CREATE TABLE  "DEPARTMENT" 
   (	"ID" NUMBER(2,0), 
	"NAME" VARCHAR2(20) NOT NULL ENABLE, 
	"FACULTY" VARCHAR2(5) NOT NULL ENABLE, 
	 CONSTRAINT "DEPARTMENT_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "STUDENT" 
   (	"ID" VARCHAR2(10), 
	"NAME" VARCHAR2(20) NOT NULL ENABLE, 
	"SURNAME" VARCHAR2(20) NOT NULL ENABLE, 
	"STUDY_YEAR" NUMBER(1,0), 
	"DEPARTMENT" NUMBER, 
	 CONSTRAINT "STUDY_YEAR_CK" CHECK (1 <= STUDY_YEAR and STUDY_YEAR <= 7) ENABLE, 
	 CONSTRAINT "STUDENT_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "COURSE" 
   (	"ID" NUMBER(4,0), 
	"NAME" VARCHAR2(30) NOT NULL ENABLE, 
	"TEACHER_ID" VARCHAR2(10), 
	"CREDITS" NUMBER(2,0), 
	 CONSTRAINT "COURSE_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "GRADE" 
   (	"STUDENT_ID" VARCHAR2(10), 
	"COURSE_ID" NUMBER(4,0), 
	"DATE" DATE, 
	"ELP" CHAR(1), 
	"VALUE" NUMBER(3,1), 
	 CONSTRAINT "GRADE_CK_ELP" CHECK ("ELP" in ('E', 'L', 'P')) ENABLE, 
	 CONSTRAINT "GRADE_CK_VALUE" CHECK ("VALUE" between 1 and 10) ENABLE
   )
/
CREATE TABLE  "SIGNUP" 
   (	"ID" NUMBER(10,0) DEFAULT  "STUDENT_COURSE_SEQ"."NEXTVAL", 
	"STUDENT_ID" VARCHAR2(10), 
	"COURSE_ID" NUMBER(4,0), 
	"YEAR" DATE, 
	 CONSTRAINT "SIGNUP_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "DUPLICATE_SIGNUP" UNIQUE ("STUDENT_ID", "COURSE_ID", "YEAR")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "TEACHER" 
   (	"ID" VARCHAR2(10), 
	"NAME" VARCHAR2(20) NOT NULL ENABLE, 
	"SURNAME" VARCHAR2(20) NOT NULL ENABLE, 
	"BASE_SALARY" NUMBER(7,2), 
	"DEPARTMENT" NUMBER, 
	 CONSTRAINT "BASE_SALARY_CK" CHECK (BASE_SALARY >= 0) ENABLE, 
	 CONSTRAINT "TEACHER_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )
/
ALTER TABLE  "COURSE" ADD CONSTRAINT "COURSE_FK_TEACHER" FOREIGN KEY ("TEACHER_ID")
	  REFERENCES  "TEACHER" ("ID") ON DELETE CASCADE ENABLE
/
ALTER TABLE  "GRADE" ADD CONSTRAINT "GRADE_FK_COURSE" FOREIGN KEY ("COURSE_ID")
	  REFERENCES  "COURSE" ("ID") ON DELETE CASCADE ENABLE
/
ALTER TABLE  "GRADE" ADD CONSTRAINT "GRADE_FK_STUDENT" FOREIGN KEY ("STUDENT_ID")
	  REFERENCES  "STUDENT" ("ID") ON DELETE CASCADE ENABLE
/
ALTER TABLE  "SIGNUP" ADD CONSTRAINT "SIGNUP_FK_COURSE" FOREIGN KEY ("COURSE_ID")
	  REFERENCES  "COURSE" ("ID") ON DELETE CASCADE ENABLE
/
ALTER TABLE  "SIGNUP" ADD CONSTRAINT "SIGNUP_FK_STUDENT" FOREIGN KEY ("STUDENT_ID")
	  REFERENCES  "STUDENT" ("ID") ON DELETE CASCADE ENABLE
/
ALTER TABLE  "STUDENT" ADD CONSTRAINT "STUDENT_FK_DEPARTMENT" FOREIGN KEY ("DEPARTMENT")
	  REFERENCES  "DEPARTMENT" ("ID") ON DELETE CASCADE ENABLE
/
ALTER TABLE  "TEACHER" ADD CONSTRAINT "TEACHER_FK_DEPARTMENT" FOREIGN KEY ("DEPARTMENT")
	  REFERENCES  "DEPARTMENT" ("ID") ON DELETE CASCADE ENABLE
/
CREATE UNIQUE INDEX  "COURSE_PK" ON  "COURSE" ("ID")
/
CREATE UNIQUE INDEX  "DEPARTMENT_PK" ON  "DEPARTMENT" ("ID")
/
CREATE UNIQUE INDEX  "DUPLICATE_SIGNUP" ON  "SIGNUP" ("STUDENT_ID", "COURSE_ID", "YEAR")
/
CREATE UNIQUE INDEX  "SIGNUP_PK" ON  "SIGNUP" ("ID")
/
CREATE UNIQUE INDEX  "STUDENT_PK" ON  "STUDENT" ("ID")
/
CREATE UNIQUE INDEX  "TEACHER_PK" ON  "TEACHER" ("ID")
/
 CREATE SEQUENCE   "STUDENT_COURSE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 5 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL
/
